[ddm] clean up symlinks more thoroughly

diff --git a/ddm b/ddm
--- a/ddm
+++ b/ddm
@@ -59,6 +59,8 @@ main () {
     fi
 
     ddm "$op" "$host"
+
+    clean_seen_dirs
 }
 
 ddm () {
@@ -175,48 +177,60 @@ sync_deps() {
 
 
 ############################################## SYNC
-# This function implements the dot-file stowing
 
+## Find operations
+find_pkg_files() {
+    local pkgDir=$1
+    find "$pkgDir" -not -type d -print0
+}
+
+find_dead_links() {
+    find "$1" -maxdepth 1 -not -type d -exec test ! -e {} \; -print0
+
+}
+
+# This function implements the dot-file stowing
 sync_up () {
     local pkgDir=$1
     local dstDir=$2
+
     # for each file in pkgDir
-    find "$pkgDir" -not -type d -print0 | \
-        while IFS= read -r -d '' pkgFile; do
-            local destFile=$(get_dest_path "$pkgDir" "$dstDir" "$pkgFile")
-            local destFileDir=$(dirname "$destFile")
+    while IFS= read -r -d '' pkgFile; do
+        local destFile=$(get_dest_path "$pkgDir" "$dstDir" "$pkgFile")
+        local destFileDir=$(dirname "$destFile")
 
-            remove_dead_siblings "$destFileDir"
+        record_seen_dir "$destFileDir"
 
-            local maybePkgFile=$(get_linked "$destFile")
+        local maybePkgFile=$(get_linked "$destFile")
 
-            debug "pkgFile = $pkgFile"
-            debug "destFile = $destFile"
-            debug "maybePkgFile = $maybePkgFile"
+        debug "pkgFile = $pkgFile"
+        debug "destFile = $destFile"
+        debug "maybePkgFile = $maybePkgFile"
 
-            if is_same "$pkgFile" "$maybePkgFile"; then
-                print_stow "$destFile"
-                continue
-            fi
+        if is_same "$pkgFile" "$maybePkgFile"; then
+            debug "$pkgFile already linked to $destFile; skipping"
+            # print_stow "$destFile"
+            continue
+        fi
 
-            if dir_contains "$pkgDir" "$maybePkgFile"; then
-                debug "rm $destFile"
-                $DRY_RUN || rm "$destFile"
-            fi
+        if dir_contains "$pkgDir" "$maybePkgFile"; then
+            debug "rm $destFile"
+            $DRY_RUN || rm "$destFile"
+        fi
 
-            if [ -e "$maybePkgFile" ]; then
-                error "Error: '$destFile' already exists ('$maybePkgFile') but is not owned by us."
-                exit 1
-            fi
+        if [ -e "$maybePkgFile" ]; then
+            error "Error: '$destFile' already exists ('$maybePkgFile') but is not owned by us."
+            exit 1
+        fi
 
-            debug "mkdir $destFileDir"
-            $DRY_RUN || mkdir -p "$destFileDir"
+        debug "mkdir $destFileDir"
+        $DRY_RUN || mkdir -p "$destFileDir"
 
-            local relPath=$(relpath "$pkgFile" "$destFileDir")
+        local relPath=$(relpath "$pkgFile" "$destFileDir")
 
-            print_stow "$destFile"
-            $DRY_RUN || ln -s "$relPath" "$destFile"
-        done
+        print_stow "$destFile"
+        $DRY_RUN || ln -s "$relPath" "$destFile"
+    done < <(find_pkg_files "$pkgDir")
 }
 
 sync_dn () {
@@ -229,23 +243,21 @@ sync_dn () {
     PATH=$pkgDir/local/bin:$PATH
 
     # for each file in pkgDir
-    find "$pkgDir" -not -type d -print0 | \
-        while IFS= read -r -d '' pkgFile; do
+    while IFS= read -r -d '' pkgFile; do
+        local destFile=$(get_dest_path "$pkgDir" "$dstDir" "$pkgFile")
+        local destFileDir=$(dirname "$destFile")
 
-            local destFile=$(get_dest_path "$pkgDir" "$dstDir" "$pkgFile")
-            local destFileDir=$(dirname "$destFile")
+        record_seen_dir "$destFileDir"
 
-            remove_dead_siblings "$destFileDir"
+        local maybePkgFile=$(get_linked "$destFile")
 
-            local maybePkgFile=$(get_linked "$destFile")
+        if dir_contains "$pkgDir" "$maybePkgFile"; then
+            print_unstow "$destFile"
+            $DRY_RUN || rm "$destFile"
+        fi
 
-            if dir_contains "$pkgDir" "$maybePkgFile"; then
-                print_unstow "$destFile"
-                $DRY_RUN || rm "$destFile"
-            fi
-
-            # TODO: remove empty directories
-        done
+        # TODO: remove empty directories
+    done < <(find_pkg_files "$pkgDir")
 }
 
 # Get what should be the destination path for a pkgFile
@@ -257,6 +269,8 @@ get_dest_path () {
     # Using parameter substitution here is much faster than using 'relpath' but
     # should be safe give how we use find to find all files in pkgDir
     local destFile=${pkgFile#$pkgDir/}
+    debug "pkgDir = $1"
+    debug "destFile = $destFile"
     echo "$dstDir/.$destFile"
 }
 
@@ -285,14 +299,34 @@ dir_contains () {
     done
 }
 
-remove_dead_siblings() {
-    local destFileDir=$1
+declare -A seenDirs=(["$HOME"]=true)
+record_seen_dir() {
+    local file=$1
 
-    find "$destFileDir" -maxdepth 1 -xtype l -print0 | \
+    while :; do
+        [ -z "$file" ] && return
+
+        [ ${seenDirs["$file"]+is_set} ] && return
+
+        seenDirs+=([$file]=true)
+
+        [ "$file" = "." -o "$file" = "/" ] && return
+
+        file=$(dirname "$file")
+    done
+}
+
+clean_seen_dirs() {
+    local printed=""
+    for dir in "${!seenDirs[@]}"; do
         while IFS= read -r -d '' deadLink; do
+            [[ -z "$printed" ]] && verbose "???"
+            printed=yes
+
             print_unstow "$deadLink"
             $DRY_RUN || rm "$deadLink"
-        done
+        done < <(find_dead_links "$dir")
+    done
 }
 
 #### Utils
@@ -318,12 +352,10 @@ is_same() {
 # join two paths together. If the second part is an absolute path, it will
 # replace the result with that
 join () {
-    local a=$1
-    local b=$2
-    if [ ${b::1} = "/" ] ; then
-        echo $b;
-    else 
-        echo "${a%/}/$b";
+    if [ ${2::1} = "/" ] ; then
+        echo $2;
+    else
+        echo "${1%/}/$2";
     fi
 }
 
